repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: mixed-line-ending
      - id: check-symlinks
      - id: detect-private-key

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false # Performance

      - id: cargo-clippy
        name: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy --all-targets --all-features -- -D warnings

  #- repo: https://github.com/notken12/licensesnip
  #  rev: f01f898e2cef002c653bde4cfe9aefe89019cbb8
  #  hooks:
  #    - id: licensesnip
  #      args: ["check"] # optionally modify the arguments for licensesnip (default arguments shown here)
  #

# TODO:
# - Integrate clippy into our IDE so we can enable it here.
# - Wait for https://github.com/j178/prek/pull/989 so we can integrate licensesnip support.
