site_name: blext

nav:
  - Overview: index.md
  - features.md
  - installation.md
  - User Guides:
    - user_guides/getting_started.md
    - user_guides/project_extensions.md
    - user_guides/script_extensions.md
    - CLI:
      - user_guides/cli/commands.md
      - user_guides/cli/locating.md
      - user_guides/cli/conforming.md
      - user_guides/cli/global_config.md
    - Integrations:
      - user_guides/integrations/ci_cd.md
      - user_guides/integrations/linting.md
      - user_guides/integrations/testing.md
      - user_guides/integrations/static_typing.md
      - user_guides/integrations/podman_docker.md
      - user_guides/integrations/pre_commit.md
    - Migrating:
      - from Existing Extension: user_guides/migrating/from_existing_extension.md
      - from Legacy Addon: user_guides/migrating/from_legacy_addon.md
  - Resources:
    - resources/extension_resources.md
    - resources/git_resources.md
  - Reference:
    - Release Notes: reference/release_notes.md
    - Policies:
      - reference/policies/versioning.md
      - reference/policies/licensing.md
      - reference/policies/contributing.md
      - reference/policies/schemas.md
    - Python API:
      - reference/python_api/blext.md
      - reference/python_api/blext_cli.md
      - reference/python_api/blext_extyp.md
      - reference/python_api/blext_pydeps.md
      - reference/python_api/blext_ui.md
      - reference/python_api/blext_uityp.md
      - reference/python_api/blext_utils.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

theme:
  language: en
  name: "material"
  palette:
    scheme: slate
    primary: red
    accent: blue
  features:
    - navigation.sections
    - content.tabs.link

plugins:
- termynal
- search
- autorefs
- privacy
- offline
- gh-admonitions
- macros
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true
          parameter_headings: false
          show_root_heading: true
          group_by_category: true
          show_category_heading: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          docstring_style: google
          merge_init_into_class: true
          separate_signature: true
          show_signature_annotations: true
          show_overloads: true
          signature_crossrefs: true
          unwrap_annotated: true
          docstring_section_style: spacy
          extensions:
            - griffe_pydantic:
              schema: true
        inventories:
          - https://installer.readthedocs.io/en/stable/objects.inv
